apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dmn-knative
spec:
  template:
    metadata:
      name: dmn-knative-v1
    spec:
      containers:
        - image: >-
            quay.io/gautric/dmn-knative:1.0
          env:
            - name: JAVA_OPTS
              value: "-Dvertx.cacheDirBase=/work/vertx"
